import { StyleSheet } from 'react-native';

const LoadStyles = StyleSheet.create({
container: {
  flex: 1,
  backgroundColor: "white",
  flexDirection: "column",
},
background: {
    flexDirection: "column",
    height: "100%",
    width: '100%',
    justifyContent: "center",
    alignItems: "center",
  },
  mainBody: {
    flexDirection: "column",
    //backgroundColor: "powderblue",
    height: "100%",
    width: '100%',
    justifyContent: "flex-start",
    alignItems: "center",
  },
  tappContainer: {
    flexDirection: "column",
    //backgroundColor: "red",
    height: "35%",
    width: '100%',
    justifyContent: "flex-end",
    alignItems: "center",
  },
  spaceContainer: {
    flexDirection: "column",
    //backgroundColor: "pink",
    height: "20%",
    width: '100%',
    justifyContent: "flex-start",
    alignItems: "center",
  },
  tappLogoContainer: {
    flexDirection: "column",
    //backgroundColor: "green",
    height: "65%",
    width: '100%',
    justifyContent: "flex-end",
    alignItems: "center",
  },
  tappLogoImage: {
    alignSelf: "center",
    height: "50%",
    width: "80%",
  },
  welcomeText: {
    textAlign: "center",
    fontSize: 50,
    fontWeight: "bold",
    color: "darkorange",
    paddingTop: 20,
  },
  tappCoinContainer: {
    flexDirection: "column",
    //backgroundColor: "green",
    height: "25%",
    width: '100%',
    justifyContent: "flex-end",
    alignItems: "center",
  },
  coinContainer: {
    flexDirection: "column",
    //backgroundColor: "pink",
    height: "90%",
    width: '60%',
    justifyContent: "flex-start",
    alignItems: "center",
  },
  coinLogoImage: {
    alignSelf: "center",
    width: 200,
    height: 200,
    resizeMode: 'contain',
  },
  buttonContainer: {
    flexDirection: "column",
    //backgroundColor: "green",
    height: "25%",
    width: '100%',
    justifyContent: "center",
    alignItems: "center",
  },
  signInContainer: {
    flexDirection: "column",
    //backgroundColor: "red",
    height: "40%",
    width: '100%',
    justifyContent: "center",
    alignItems: "center",
  },
  signInButton: {
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    height: "65%",
    width: '50%',
    borderWidth: 2,
    borderColor: "darkorange",
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  signInText: {
    textAlign: "center",
    fontSize: 25,
    fontWeight: "bold",
    color: "darkorange",
  },
  createAccountContainer: {
    flexDirection: "column",
    //backgroundColor: "pink",
    height: "40%",
    width: '100%',
    justifyContent: "center",
    alignItems: "center",
  },
  createAccountButton: {
    backgroundColor: "midnightblue",
    justifyContent: "center",
    alignItems: "center",
    height: "65%",
    width: '50%',
    borderWidth: 2,
    borderColor: "darkorange",
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  createAccountText: {
    textAlign: "center",
    fontSize: 25,
    fontWeight: "bold",
    color: "white",
  },

});

export default LoadStyles;